### ISSUE TITLE
is_number returns true for an any_type after resolving a boolean

### ISSUE THREAD

**Issue by MineBill** [BlackMATov/meta.hpp#106]
While creating a function to display members of a reflected class using imgui, i kept triggering an assert because i wasn't providing a number value to one of it's functions:

```cpp
bool InspectorWindow::draw_property(meta_hpp::uvalue prop_value, meta_hpp::member const& member, meta_hpp::uvalue& ptr)
{
    auto const prop_type = prop_value.get_type().as_pointer().get_data_type();
    auto& metadata = member.get_metadata();
    if (prop_type.is_number()) {
        ImGuiDataType type;
        if (prop_value.is<f32*>()) {
            ...
        } else if (prop_value.is<...>()) {
            ...
        }

        if (ImGui::InputScalar("", type, data_ptr)) {
            ...
        }
    } else if (prop_value.is<bool*>()) {
        if (ImGui::Checkbox("", prop_value.as<bool*>())) {
            ...
        }
    ...
```

After a while, i realized that when attempting to draw a boolean property, `prop_type.is_number()` would return true, calling into InputScalar with a `bool*`. The fix is easy enough, changing the if condition to `prop_type.is_number() && !prop_value.is<bool*>()` but that made me question whether this library intended for booleans to be treated as numbers or not.

**Comment by BlackMATov** [comment]
Yeah, it's okay. "Numbers" in the library are a conjunction of integral types ([std::is_integral](https://en.cppreference.com/w/cpp/types/is_integral)) and floating point types ([std::is_floating_point](https://en.cppreference.com/w/cpp/types/is_floating_point)). I should have named it "arithmetic" like it was in C++ ([std::is_arithmetic](https://en.cppreference.com/w/cpp/types/is_arithmetic)) but what's done is done :-)

**Comment by MineBill** [comment]
Great! In that case then, this issue should be closed.
