### ISSUE TITLE
duplicate registration

### ISSUE THREAD

**Issue by gxw8202** [BlackMATov/meta.hpp#107]
I have noticed that when Creating generic classes separately in multiple DLLs can result in duplicate registration of type data to type_degister.

**Comment by BlackMATov** [comment]
Hello!

Each shared library has its own type registry. To use classes across libraries, we need to mark these classes with `META_HPP_DEFINE_SHARED_TYPE` macro. After that, for example, we can use an instance of a class from library A as argument to a function from library B.

By default, only fundamental types are shared. (https://github.com/BlackMATov/meta.hpp/blob/main/headers/meta.hpp/meta_detail/type_sharing.hpp#L329)

With this system, we can share and use classes which even not visible in current compilation unit or library, reload libraries in runtime and so on. (https://github.com/BlackMATov/meta.hpp/blob/main/develop/unshared/meta_shared_exe/meta_shared_usage.cpp)

**Comment by gxw8202** [comment]
Test passed. Thanks
