### ISSUE TITLE
Doesn't compile with C++23 in visual studio 2022 with /std:c++latest

### ISSUE THREAD

**Issue by innochenti** [BlackMATov/meta.hpp#17]
steps to repro: 
1. **set C++ Language Standard** to **Preview - Features from the Latest C++ Working Draft (/std:c++latest)**
_Error:_

meta.hpp\meta_base\fixed_function.hpp(81,32): error C4996: 'std::aligned_storage_t': warning STL4034: std::aligned_storage and std::aligned_storage_t are deprecated in C++23. Prefer alignas(T) std::byte t_buff[sizeof(T)]. You can define _SILENCE_CXX23_ALIGNED_STORAGE_DEPRECATION_WARNING or _SILENCE_ALL_CXX23_DEPRECATION_WARNINGS to acknowledge that you have received this warning.

**Comment by BlackMATov** [comment]
Your wish has been granted :-)
