### ISSUE TITLE
Memeber as getter and setter

### ISSUE THREAD

**Issue by MohammadMDSA** [BlackMATov/meta.hpp#62]
Hi,
Thank you for the great library. Hoping to build my game engine reflection on it.
Is it possible for you to add support for adding members without a pointer to a specific region of a class and by specifying just a getter and setter function?

**Comment by BlackMATov** [comment]
Hello! Thank you :-)

I think you want to have something like properties, but at this stage of development, I don't want to add features that are not in the С++ itself. And, of course, you can use two bound methods as an imaginary property on your side.
