### ISSUE TITLE
Resolve generic std::tuple

### ISSUE THREAD

**Issue by jcarraror** [BlackMATov/meta.hpp#72]
Is it possible to identify or resolve a ```std::tuple<Args...>```? What i want to do is, if a ```meta::any_type``` is a ```std::tuple<...>```, i want to resolve the internal types of this tuple. There's any way of doing this or i only can resolve a deterministic type?

**Comment by jcarraror** [comment]
Parallel to this, there's also some way to get a c++ type-like from the ```meta::any_type```?

**Comment by BlackMATov** [comment]
> Is it possible to identify or resolve a `std::tuple<Args...>`? What i want to do is, if a `meta::any_type` is a `std::tuple<...>`, i want to resolve the internal types of this tuple. There's any way of doing this or i only can resolve a deterministic type?

Such classes can be resolved without registering a specific type, and even get the type of its template arguments.
For example:

```cpp
using my_tuple = std::tuple<int, float>;
meta::class_type my_tuple_type = meta::resolve_type<my_tuple>();

REQUIRE(my_tuple_type.get_arity() == 2);
CHECK(my_tuple_type.get_argument_type(0) == meta::resolve_type<int>());
CHECK(my_tuple_type.get_argument_type(1) == meta::resolve_type<float>());
```

But without registering a specific type, you will not be able to use other functions, such as calling methods or constructors.

**Comment by BlackMATov** [comment]
> Parallel to this, there's also some way to get a c++ type-like from the `meta::any_type`?

No, because xxx_type from Meta.hpp is runtime (dynamic) type information. This trick is only available with static reflection, but that's a completely different story :-)

**Comment by jcarraror** [comment]
Got it, but there is some way of identifying a tuple in a vector of ```meta::arguments``` from a ```meta::method```. I want to identify the tuple in a vector of arguments to be able to get the internal tuple types properly.

**Comment by jcarraror** [comment]
> > I want to identify the tuple in a vector of arguments to be able to get the internal tuple types properly. From a already registered class, i mean.
> 
> To get specific types of tuples, you can compare their type IDs. If I understood the problem correctly. Every meta type has `get_id` method to do it. Every `argument` also has `get_type`.

I know about this methods, but my point is about identifying if a meta type is a generic tuple. I want to identify if a meta type is any kind of tuple, so i can have a different treatment to these types.

**Comment by BlackMATov** [comment]
Eh, I see. Unfortunately, at the moment I can’t imagine how to implement this (at runtime) without registering all specific classes :-(
