### ISSUE TITLE
Missing pdb when trying to run

### ISSUE THREAD

**Issue by AaronFrans** [BlackMATov/meta.hpp#90]
When I launch my program, it crashes when getting to the code containing the meta functions.
It says I'm missing the ucrtbase.pdb.
![image](https://github.com/BlackMATov/meta.hpp/assets/61042747/f7ab9bcc-7678-4bdd-9b8b-7689142a918b)

**Comment by BlackMATov** [comment]
"ucrtbase.pdb" is an internal msvc file with debug symbols. Try to debug your application and find out what happened before the crash. Without the reproducing code, I can't help. Maybe you are trying to call a missing function or something else, I don't know.

**Comment by AaronFrans** [comment]
Yep, it turns out I was getting the error because I was on release mode. I figured out the original error as well, thanks for the fast response!
