### ISSUE TITLE
How to support std::shared_ptr for upcast

### ISSUE THREAD

**Issue by gxw8202** [BlackMATov/meta.hpp#92]
for example,
struct A{}
struct B:A{}
class test
{
std::shared_ptr<B> calc()
{
return std::make_shared<B>();
}

how to upcast the result of calc method as std::shared_ptr<A> by reflection.

**Comment by BlackMATov** [comment]
Hello! 

If you have `uvalue` with  `shared_ptr<T>` inside, you can call `uvalue::unmap` method to get `uvalue` with raw pointer `T*` from `shared_ptr`. This will be analogous to a call `shared_ptr::get`.

But be careful with the lifetime of the smart pointer, otherwise the `uvalue` may contains a dangling pointer.

**Comment by BlackMATov** [comment]
P.S.

I have some ideas for a new mechanism that would allow smart pointers to be used as method instances. But it has not yet been implemented and not thought out in detail.

**Comment by gxw8202** [comment]
struct Result
{
    AGL_REFL_ENABLE_POLY_INFO()
public:
    int m = 100;
   
   Result(int _m = 0) :m(_m) {}
};
typedef std::shared_ptr< Result> ResultSPtr;

struct NewResult :Result
{
    AGL_REFL_ENABLE_POLY_INFO(Result)
public:
    int n = 200;

    NewResult(int _m = 1) :Result(_m) {}
};
typedef std::shared_ptr<NewResult> NewResultSPtr;

class shape {
    AGL_REFL_ENABLE_POLY_INFO()
public:
    shape() = default;
    shape(const shape&) = default;
    virtual ~shape() = default;

    virtual int get_area() const = 0;

    virtual NewResultSPtr get_area_result() const = 0;
};
class rectangle : public shape {
    AGL_REFL_ENABLE_POLY_INFO(shape)
public:
    explicit rectangle(int width, int height)
        : width_{ width }
        , height_{ height } {}

    int get_width() const {
        return width_;
    }

    int get_height() const {
        return height_;
    }

    int get_area() const override {
        return width_ * height_;
    }
    virtual NewResultSPtr get_area_result() const
    {
        return std::make_shared<NewResult>(width_*height_);
    }
private:
    int width_{};
    int height_{};
};
int main()
{  
    agl::refl::class_<Result>();
    agl::refl::class_<NewResult>();

    agl::refl::class_<shape>().method_("get_area", &shape::get_area)
        .method_("get_area_result",&shape::get_area_result);
    agl::refl::class_<rectangle>().constructor_<int, int>()
        .method_("get_width", &rectangle::get_width)
        .method_("get_height", &rectangle::get_height);

    // resolves a class type by static class type
    const agl::refl::class_type rectangle_type = agl::refl::resolve_type<rectangle>();

    // prints all class methods
    for (const method& method : rectangle_type.get_methods()) {
        std::cout << std::format("  + {}/{}\n",
            method.get_name(),
            method.get_type().get_arity());
    }

    const class_type shape_type = resolve_type<shape>();
    const method shapde_area = shape_type.get_method("get_area");

    std::shared_ptr<shape> shape1 = std::make_shared<rectangle>(1,8);
    int x = shapde_area.invoke(shape1.get()).as<int>();

    const method shape_area_ret = shape_type.get_method("get_area_result");
    uvalue r = shape_area_ret.invoke(shape1.get());
    if (r.get_type().is_class())
    {
        class_bitflags clsflgs = r.get_type().as_class().get_flags();
        if (clsflgs.has(class_flags::is_shared_ptr)) {
            int m = 0;
            m++;
       //     ResultSPtr ret = std::dynamic_pointer_cast<Result>(r);
        }
    }
    ResultSPtr ret = shape_area_ret.invoke(shape1.get()).as<ResultSPtr>();
   // std::cout << x << std::endl;
}

**Comment by gxw8202** [comment]
![错误](https://github.com/BlackMATov/meta.hpp/assets/17743181/ba68bf24-964c-4e5a-a879-a9a0863d85c3)

**Comment by gxw8202** [comment]
thanks you for your reply.
at 104 line throw upcast exception.May I ask how to resolve this error?

**Comment by BlackMATov** [comment]
So, with this code preview it is difficult to understand what is happening, but as far as I can see you are trying to take a shared pointer to a base class from an `uvalue` that contains a shared pointer to a derived class.

Unfortunately, this type of casts is not supported. Because, for the reflection system, these completely different types. Upcasting is supported only for raw pointers.

Consider the `uvalue` a regular `std::any` with some bonuses, and not a thing that can do everything in the world :-)
