### ISSUE TITLE
How to `release` the object from a `uvalue` or create instances on the heap

### ISSUE THREAD

**Issue by globberwops** [BlackMATov/meta.hpp#99]
Hi Matvey,

I'm currently on the lookout for an actively maintained, modern replacement for `ponder`.
`ponder` somehow clashes with `spdlog`, which I would very much like to use.

One of my use cases for a reflection library is reflecting on enums, which works very well.
However, I am struggling with my second use case.

I want to construct derived class instances by name-as-string at runtime as pointers to their base class:
1. Register derived class
2. Resolve specific derived class type by string
3. Construct specific derived class as pointer-to-base on the heap

This is where I'm at right now.
Of course, the `Rectangle` instance is deleted when `ushape` goes out of scope.

`create_at` on the other hand is overkill for my use case, since I do not want to manage buffers for `placement new`.

```cpp
#include <gtest/gtest.h>

#include <fmt/core.h>
#include <meta.hpp/meta_all.hpp>
#include <meta.hpp/meta_binds.hpp>
#include <meta.hpp/meta_registry.hpp>

namespace {

class Shape {
  META_HPP_ENABLE_POLY_INFO();

public:
  virtual ~Shape() = default;

  virtual int GetWidth() const = 0;
  virtual int GetHeight() const = 0;
};

class Rectangle : public Shape {
  META_HPP_ENABLE_POLY_INFO(Shape);

public:
  Rectangle(int width, int height) : width_(width), height_(height) {}

  int GetWidth() const override { return width_; }
  int GetHeight() const override { return height_; }

private:
  int width_;
  int height_;
};

TEST(MetaHppTest, ClassByName) {
  namespace meta = meta_hpp;

  // Register
  meta::class_<Rectangle>()
      .constructor_<int, int>()
      .method_("GetWidth", &Rectangle::GetWidth)
      .method_("GetHeight", &Rectangle::GetHeight);

  const meta::scope test_scope = meta::static_scope_("MetaHppTest/ClassByName")
                                     .typedef_<Rectangle>("Rectangle");

  // Resolve
  auto *shape = []() {
    const meta::scope test_scope =
        meta::static_scope_("MetaHppTest/ClassByName");
    const auto rectangle_type = test_scope.get_typedef("Rectangle").as_class();
    auto ushape = rectangle_type.create(10, 20);
    auto *shape = ushape.try_as<Shape>();
    return shape;
  }();

  //  Check
  ASSERT_TRUE(shape != nullptr);

  fmt::print("[    LOG   ] Width: {}\n", shape->GetWidth());
  fmt::print("[    LOG   ] Height: {}\n", shape->GetHeight());

  delete shape;
}

} // namespace

```

Cheers,
Martin

**Comment by BlackMATov** [comment]
Hello Martin!
Thank you for your interest in this library.

`meta.hpp` has different policies for constructors (`as_object`, `as_raw_pointer`, `as_shared_pointer`, `as_unique_pointer`). By default, it uses `as_object`. This means that objects created by such constructors will have the lifetime of their container (`uvalue`). Think of it as using `std::any` in regular C++ (`std::any a = rectangle{}`)

In your case, I think you'd prefer to use another policy. For example, you can use `as_raw_pointer`. This policy means that object will be created on heap by `new` under the hood (`std::any a = new rectangle{}`). The returned `uvalue` in this case will contain a raw pointer to the created object. But don't forget to delete the instance to avoid memory leak.

Little example:

```cpp
meta::class_<shape>()
    .method_("get_area", &shape::get_area);

meta::class_<rectangle>()
    .constructor_<int, int>(meta::constructor_policy::as_raw_pointer)
    .method_("get_width", &rectangle::get_width)
    .method_("get_height", &rectangle::get_height);

const meta::scope shapes = meta::local_scope_("shapes")
    .typedef_<rectangle>("rectangle");

// resolve a class type
const meta::class_type rectangle_type = shapes.get_typedef("rectangle").as_class();
CHECK(rectangle_type == meta::resolve_type<rectangle>());

// create an instance (operator new under the hood, because it uses the `as_raw_pointer` policy)
meta::uvalue rectangle_instance = rectangle_type.create(10, 20);
// uvalue contains a pointer to the instance in this case
CHECK(rectangle_instance.get_type() == meta::resolve_type<rectangle*>());

// receive the instance pointer with downcast to the base `shape` class
shape* s = rectangle_instance.as<shape*>();

CHECK(s);
CHECK(s->get_area() == 200);

// delete the instance
delete s;
```

**Comment by globberwops** [comment]
Thank you so much for the quick response.

This looks even better than anything I thought the solution could be!

Congrats on this amazing lib, I like it a lot so far 👍🏻
